version: "3"
services:
  ngnix:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "/usr/src/app/node_modules"
      - "./frontend:/usr/src/app"
    stdin_open: true
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: app_backend
    volumes:
      - "/usr/src/app/node_modules"
      - "./backend:/usr/src/app"
    restart: always

  # mysql:
  #   build:
  #     context: ./mysql
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - "./mysql/mysql_data:/val/lib/mysql"
  #     - "./mysql/sqls/:/docker-entrypoint-initdb.d/"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 1234
  #     MYSQL_DATABASE: myapp
